# For more information: https://laravel.com/docs/sail
# docker run --name=rakoza -dp 8888:80 -v "$(pwd)"/src/vendor:/var/www/html/vendor -v "$(pwd)"/src/storage/app:/var/www/html/storage/app laravel:1.5
version: '3'
services:
    # Naziv servisa se ne moze uzeti iz env varijable, zato je i bolje da ovaj file ide u client's directory
    app:
        build:
            context: ../apps/${APP_SRC}
            # dockerfile: Dockerfile

        image: nopus:${APP_SRC}

        # treba mi zbog redisa i mysql-a, ako se pokrecu na host-u
        extra_hosts:
            - 'host.docker.internal:host-gateway'

        # volumeni na hostu
        volumes:
            - ../apps/${APP_SRC}/vendor:/var/www/html/vendor
            - ./storage:/var/www/html/storage/app
            - .env:/var/www/html/.env

        # env variables, ovako ih prosljedjujemo u kontainer
        # VIRTUAL_HOST - koristi se u nginx-proxy kontejneru za konfiguraciju virtuelnog host-a
        #
        # Vidi skript `start-container` za upotrebu ovih env varijabli
        # TZ - podesavamo vremensku zonu u docker container-u
        # USER_UID - uid apache servisa koji se pokrece u docker container-u
        # USER_GID - gid apache servisa koji se pokrece u docker container-u
        environment:
            VIRTUAL_HOST: ${APP_DOMAIN}
            TZ: ${TZ}
            USER_UID: ${USER_UID}
            USER_GID: ${USER_GID}

networks:
    default:
        external:
            name: nginx-proxy-net
